//! Raw FFI bindings to LibRaw's C API, generated by bindgen from the system headers.
//! Use the safe wrapper in `iris-raw` instead of this crate directly.

#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case, dead_code, unnecessary_transmutes)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
